style_img = samples_cora_100
content_img = coefficients
epochs = 1000
training=true
model=gcn
trained_on=gap
Run:
	python3 main.py --train $(train) --epochs $(epochs) --model $(model) --need_training $(training) --trained_on=$(trained_on)